import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useExam } from '../context/ExamContext'
import './Report.css'

export default function Report() {
  const navigate = useNavigate()
  const { sessionData } = useExam()

  /* Redirect if no session data */
  useEffect(() => {
    if (!sessionData) navigate('/')
  }, [sessionData, navigate])

  if (!sessionData) return null

  const {
    durationSec,
    questionsAnswered,
    wordCount,
    avgConfidence,
    transcript,
    date,
  } = sessionData

  const score      = calcScore(avgConfidence, questionsAnswered, durationSec)
  const scoreGrade = getGrade(score)
  const timeStr    = fmtTime(durationSec)

  /* ── Download report ── */
  function downloadReport() {
    const lines = [
      'PASSGP AI ORAL EXAMINER — SESSION REPORT',
      '═'.repeat(50),
      '',
      `Date               : ${date}`,
      `Session Duration   : ${timeStr}`,
      `Questions Covered  : ${questionsAnswered}`,
      `Words Spoken       : ${wordCount}`,
      `Avg Confidence     : ${avgConfidence}%`,
      `Performance Score  : ${score}/100  (${scoreGrade})`,
      '',
      '═'.repeat(50),
      'TRANSCRIPT',
      '═'.repeat(50),
      '',
      ...transcript.map(
        (t) => `[${t.time}] ${t.role.toUpperCase().padEnd(12)}: ${t.text}`
      ),
      '',
      '═'.repeat(50),
      'EXAMINER FEEDBACK',
      '═'.repeat(50),
      '',
      getFeedback(score),
      '',
      '─'.repeat(50),
      'Generated by PassGP AI Oral Examiner MVP',
      `Exported: ${new Date().toLocaleString('en-AU')}`,
    ]

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `passgp-report-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="rp-root">
      <div className="grain-overlay" />
      <div className="bracket tl" /><div className="bracket tr" />
      <div className="bracket bl" /><div className="bracket br" />

      <div className="rp-container">

        {/* Header */}
        <div className="rp-header">
          <div className="rp-header-left">
            <div className="rp-brand-dot" />
            <div>
              <div className="rp-brand-name">PASSGP</div>
              <div className="rp-brand-sub">Session Report · {date}</div>
            </div>
          </div>
          <div className="rp-score-badge">
            <div className="rp-score-num">{score}</div>
            <div className="rp-score-label">/ 100</div>
            <div className={`rp-score-grade grade-${scoreGrade.toLowerCase()}`}>{scoreGrade}</div>
          </div>
        </div>

        {/* Metric cards */}
        <div className="rp-metrics">
          <MetricCard label="Duration"    value={timeStr}               icon="⏱" />
          <MetricCard label="Questions"   value={questionsAnswered}      icon="📋" />
          <MetricCard label="Confidence"  value={`${avgConfidence}%`}   icon="🎯" />
          <MetricCard label="Words"       value={wordCount}              icon="💬" />
        </div>

        {/* Performance breakdown */}
        <div className="rp-section">
          <h3 className="rp-section-title">Performance Breakdown</h3>
          <div className="rp-bars">
            <BarRow label="Clinical Knowledge"     pct={Math.min(100, avgConfidence + 2)} />
            <BarRow label="Communication Clarity"  pct={Math.min(100, avgConfidence - 3)} />
            <BarRow label="Structured Approach"    pct={Math.min(100, avgConfidence + 5)} />
            <BarRow label="Safety &amp; Red Flags"     pct={Math.min(100, avgConfidence - 1)} />
            <BarRow label="Time Management"        pct={questionsAnswered > 2 ? 82 : 60} />
          </div>
        </div>

        {/* Feedback */}
        <div className="rp-section">
          <h3 className="rp-section-title">Examiner Feedback</h3>
          <p className="rp-feedback-text">{getFeedback(score)}</p>
        </div>

        {/* Transcript */}
        <div className="rp-section">
          <h3 className="rp-section-title">Session Transcript</h3>
          <div className="rp-transcript">
            {transcript.length === 0 ? (
              <p className="rp-empty">No transcript recorded.</p>
            ) : (
              transcript.map((t, i) => (
                <div key={i} className={`rp-turn rp-turn-${t.role}`}>
                  <div className="rp-turn-meta">
                    <span className="rp-turn-role">{t.role === 'examiner' ? 'EXAMINER' : 'CANDIDATE'}</span>
                    <span className="rp-turn-time">{t.time}</span>
                  </div>
                  <p className="rp-turn-text">{t.text}</p>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Action buttons */}
        <div className="rp-actions">
          <button className="rp-btn rp-btn-download" onClick={downloadReport}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
            Download Report
          </button>
          <button className="rp-btn rp-btn-new" onClick={() => navigate('/exam')}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <path d="M12 1a3 3 0 00-3 3v8a3 3 0 006 0V4a3 3 0 00-3-3z" />
              <path d="M19 10v2a7 7 0 01-14 0v-2" />
              <path d="M12 19v4m-4 0h8" />
            </svg>
            New Session
          </button>
        </div>

      </div>
    </div>
  )
}

/* ── Sub-components ── */
function MetricCard({ label, value, icon }) {
  return (
    <div className="rp-metric-card">
      <div className="rp-metric-icon">{icon}</div>
      <div className="rp-metric-val">{value}</div>
      <div className="rp-metric-label">{label}</div>
    </div>
  )
}

function BarRow({ label, pct }) {
  return (
    <div className="rp-bar-row">
      <div className="rp-bar-label">{label}</div>
      <div className="rp-bar-track">
        <div className="rp-bar-fill" style={{ '--pct': pct + '%' }} />
      </div>
      <div className="rp-bar-pct">{pct}%</div>
    </div>
  )
}

/* ── Helpers ── */
function fmtTime(sec) {
  const m = String(Math.floor(sec / 60)).padStart(2, '0')
  const s = String(sec % 60).padStart(2, '0')
  return `${m}:${s}`
}

function calcScore(conf, questions, sec) {
  const base   = conf || 75
  const qBonus = Math.min(questions * 3, 15)
  const tBonus = sec > 60 ? 5 : 0
  return Math.min(100, Math.round(base * 0.8 + qBonus + tBonus))
}

function getGrade(score) {
  if (score >= 85) return 'PASS'
  if (score >= 70) return 'MERIT'
  return 'REVIEW'
}

function getFeedback(score) {
  if (score >= 85)
    return 'Excellent performance. You demonstrated a systematic clinical approach with clear communication and appropriate safety netting. Your structured responses showed strong knowledge of GP examination standards. Continue practising to maintain this standard.'
  if (score >= 70)
    return 'Good performance overall. You covered the key clinical domains but there were some opportunities to provide more structured differential diagnoses and elaborate on safety netting. Focus on using the SEA framework consistently and addressing patient-centred communication.'
  return 'This session highlighted areas for development. Focus on structuring your responses using the SNAP or RICE frameworks, ensuring red flag identification is explicit and early. Review core GP consultation models and practise case scenarios with a supervisor.'
}
